//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalProjectADID {
	
	
	public partial class main {
		
		protected System.Web.UI.WebControls.Content body;
		
		protected System.Web.UI.WebControls.HyperLink botButton;
		
		protected System.Web.UI.WebControls.HyperLink wgButton;
		
		protected System.Web.UI.WebControls.HyperLink credButton;
		
		protected System.Web.UI.WebControls.HyperLink addBot;
		
		protected System.Web.UI.WebControls.HyperLink addWG;
		
		protected System.Web.UI.WebControls.HyperLink addCred;
	}
}
