//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalProjectADID {
	
	
	public partial class masterPage {
		
		protected System.Web.UI.WebControls.ContentPlaceHolder navBar;
		
		protected System.Web.UI.WebControls.HyperLink homeLink;
		
		protected System.Web.UI.WebControls.HyperLink navbarDropdownMenuLink;
		
		protected System.Web.UI.WebControls.HyperLink usersLink;
		
		protected System.Web.UI.WebControls.HyperLink defaultLink;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder body;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder footer;
	}
}
